import type { RunState } from "../state/types.js";

export type WorkflowStage = RunState["stage"];
const transitions: Partial<Record<WorkflowStage, readonly WorkflowStage[]>> = {
  CREATED: ["PREFLIGHT"], PREFLIGHT: ["BASELINE_CREATED", "FAILED", "ESCALATED"], BASELINE_CREATED: ["BASELINE_GATES_RUNNING"],
  BASELINE_GATES_RUNNING: ["BASELINE_CAPTURED", "FAILED"], BASELINE_CAPTURED: ["ACCEPTANCE_CRITERIA_GENERATING"],
  ACCEPTANCE_CRITERIA_GENERATING: ["ACCEPTANCE_CRITERIA_VALIDATING", "ESCALATED"], ACCEPTANCE_CRITERIA_VALIDATING: ["ORACLE_DESIGNING", "ESCALATED"],
  ORACLE_DESIGNING: ["ORACLE_VALIDATING", "ESCALATED"], ORACLE_VALIDATING: ["PLANNING", "ESCALATED"], PLANNING: ["PLAN_VALIDATION", "ESCALATED"],
  PLAN_VALIDATION: ["IMPLEMENTING", "ESCALATED"], IMPLEMENTING: ["IMPLEMENTATION_CHECKPOINT", "FAILED", "ESCALATED"], IMPLEMENTATION_CHECKPOINT: ["GATES_RUNNING", "FAILED"],
  GATES_RUNNING: ["REPOSITORY_REVIEWING", "INCREMENTAL_REVIEW", "FAILED"], INCREMENTAL_REVIEW: ["REPOSITORY_REVIEWING", "ESCALATED"],
  REPOSITORY_REVIEWING: ["REQUIREMENTS_REVIEWING", "ESCALATED"], REQUIREMENTS_REVIEWING: ["REVIEWS_MERGING", "ESCALATED"],
  REVIEWS_MERGING: ["FINDINGS_VALIDATION", "ESCALATED"], FINDINGS_VALIDATION: ["PROGRESS_EVALUATION", "ESCALATED"],
  PROGRESS_EVALUATION: ["REPAIRING", "FINAL_AUDIT", "FAILED", "ESCALATED"], REPAIRING: ["REPAIR_CHECKPOINT", "FAILED", "ESCALATED"],
  REPAIR_CHECKPOINT: ["GATES_RUNNING", "FAILED"], FINAL_AUDIT: ["SUCCEEDED", "FAILED", "ESCALATED"],
  HANDOFF_GENERATING: ["HANDOFF_VALIDATING", "ESCALATED"], HANDOFF_VALIDATING: ["SESSION_RESTARTING", "ESCALATED"], SESSION_RESTARTING: ["PREFLIGHT", "ESCALATED"]
};

const terminal = new Set<WorkflowStage>(["SUCCEEDED", "FAILED", "ESCALATED"]);
export function canTransition(from: WorkflowStage, to: WorkflowStage): boolean {
  if (!terminal.has(from) && (to === "FAILED" || to === "ESCALATED")) return true;
  return transitions[from]?.includes(to) ?? false;
}
export function assertTransition(from: WorkflowStage, to: WorkflowStage): void { if (!canTransition(from, to)) throw new Error(`invalid workflow transition: ${from} -> ${to}`); }
export const workflowTransitions = transitions;
