import { access, readFile } from "node:fs/promises";
import path from "node:path";
import { writeTextArtifact } from "../workflow/artifacts.js";
import { redact } from "../telemetry/redact.js";
import { z } from "zod";

export const handoffHeadings = ["Identity", "Objective", "Current status", "Acceptance criteria", "Decisions and rationale", "Repository state", "Runtime and model identity", "Files changed", "Validation evidence", "Review state", "Constraints and non-goals", "Exact next actions", "References"] as const;
export interface HandoffData { runId: string; previousSessionId: string; newSessionRole: string; stage: string; iteration: number; objective: string; definitionOfDone: string; completed: string[]; inProgress: string[]; notStarted: string[]; acceptanceCriteria: Array<{ id: string; requirement: string; status: string; evidence: string[] }>; decisions: string[]; repository: { path: string; branch: string; baselineCommit: string; currentCommit: string; dirty: boolean }; runtime: string[]; filesChanged: Array<{ path: string; purpose: string }>; gates: string[]; review: { confirmed: string[]; rejected: string[]; unresolved: string[] }; constraints: string[]; nextActions: string[]; references: string[]; }
export const handoffAbstractionSchema = z.object({ completed: z.array(z.string()).default([]), inProgress: z.array(z.string()).default([]), notStarted: z.array(z.string()).default([]), decisions: z.array(z.string()).default([]), filePurposes: z.record(z.string(), z.string()).default({}), nextActions: z.array(z.string().min(1)).min(1) });
export type HandoffAbstraction = z.infer<typeof handoffAbstractionSchema>;
export function applyHandoffAbstraction(data: HandoffData, abstraction: HandoffAbstraction): HandoffData { return { ...data, completed: abstraction.completed, inProgress: abstraction.inProgress, notStarted: abstraction.notStarted, decisions: abstraction.decisions, filesChanged: data.filesChanged.map((file) => ({ ...file, purpose: abstraction.filePurposes[file.path] ?? file.purpose })), nextActions: abstraction.nextActions }; }
const bullets = (values: string[]) => values.length ? values.map((value) => `- ${value}`).join("\n") : "- None";
export function renderHandoff(data: HandoffData): string {
  const safe = redact(data) as HandoffData;
  return `# Session Handoff\n\n## Identity\n- Run ID: ${safe.runId}\n- Previous session ID: ${safe.previousSessionId}\n- New session role: ${safe.newSessionRole}\n- Workflow stage and iteration: ${safe.stage} / ${safe.iteration}\n\n## Objective\n- ${safe.objective}\n- Definition of done: ${safe.definitionOfDone}\n\n## Current status\n### Completed\n${bullets(safe.completed)}\n### In progress\n${bullets(safe.inProgress)}\n### Not started\n${bullets(safe.notStarted)}\n\n## Acceptance criteria\n${bullets(safe.acceptanceCriteria.map((item) => `${item.id}: ${item.requirement} [${item.status}] evidence=${item.evidence.join(", ") || "none"}`))}\n\n## Decisions and rationale\n${bullets(safe.decisions)}\n\n## Repository state\n- Repository/worktree path: ${safe.repository.path}\n- Branch: ${safe.repository.branch}\n- Baseline commit: ${safe.repository.baselineCommit}\n- Current commit: ${safe.repository.currentCommit}\n- Dirty state: ${safe.repository.dirty}\n\n## Runtime and model identity\n${bullets(safe.runtime)}\n\n## Files changed\n${bullets(safe.filesChanged.map((item) => `${item.path}: ${item.purpose}`))}\n\n## Validation evidence\n${bullets(safe.gates)}\n\n## Review state\n### Confirmed findings\n${bullets(safe.review.confirmed)}\n### Rejected findings and why\n${bullets(safe.review.rejected)}\n### Unresolved findings\n${bullets(safe.review.unresolved)}\n\n## Constraints and non-goals\n${bullets(safe.constraints)}\n\n## Exact next actions\n${bullets(safe.nextActions)}\n\n## References\n${bullets(safe.references)}\n`;
}
export async function writeHandoff(runDirectory: string, sequence: number, role: string, data: HandoffData): Promise<string> { return writeTextArtifact(runDirectory, `handoffs/${sequence}-${role}-handoff.md`, renderHandoff(data)); }

export async function validateHandoff(file: string, data: HandoffData, options: { maxTokens: number; secretValues?: string[]; actualRepository?: HandoffData["repository"]; expectedRuntime?: string[] }): Promise<void> {
  const absolute = path.resolve(file); const root = path.resolve(path.dirname(path.dirname(file))); if (!absolute.startsWith(`${root}${path.sep}`)) throw new Error("handoff path escapes run directory"); const markdown = await readFile(absolute, "utf8");
  for (const heading of handoffHeadings) if (!markdown.includes(`## ${heading}`)) throw new Error(`handoff is missing heading: ${heading}`);
  if (Math.ceil(Buffer.byteLength(markdown, "utf8") / 4) > options.maxTokens || Buffer.byteLength(markdown, "utf8") > options.maxTokens * 6) throw new Error("handoff exceeds token or byte limit");
  for (const expected of [data.runId, data.stage, data.newSessionRole, data.repository.path, data.repository.branch, data.repository.baselineCommit, data.repository.currentCommit]) if (!markdown.includes(expected)) throw new Error(`handoff deterministic field mismatch: ${expected}`);
  if (options.actualRepository && JSON.stringify(options.actualRepository) !== JSON.stringify(data.repository)) throw new Error("handoff Git state does not match the repository"); for (const identity of options.expectedRuntime ?? []) if (!data.runtime.includes(identity) || !markdown.includes(identity)) throw new Error(`handoff runtime identity mismatch: ${identity}`);
  if (!data.nextActions.length) throw new Error("handoff exact next actions are empty");
  for (const reference of data.references) { if (!markdown.includes(reference)) throw new Error(`handoff omitted reference: ${reference}`); await access(path.isAbsolute(reference) ? reference : path.resolve(data.repository.path, reference)); }
  for (const finding of data.review.unresolved) if (!markdown.includes(finding)) throw new Error(`handoff omitted unresolved finding: ${finding}`);
  for (const gate of data.gates.filter((value) => /failed|required/i.test(value))) if (!markdown.includes(gate)) throw new Error(`handoff omitted failed required gate: ${gate}`);
  if (/\.env(?:\s|:|=)/i.test(markdown)) throw new Error("handoff contains forbidden .env content/reference"); for (const secret of options.secretValues ?? []) if (secret && markdown.includes(secret)) throw new Error("handoff contains a secret value");
}
