import { createHash } from "node:crypto";
import { lookup } from "node:dns/promises";
import { isIP as netIsIP } from "node:net";

export interface WebReference { url: string; bytes: number; contentType: string; sha256: string; content: string; }
export interface WebOptions { fetcher?: typeof fetch; resolver?: typeof lookup; maxBytes?: number; timeoutMs?: number; maxRedirects?: number; }
function privateAddress(address: string): boolean { const normalized = address.replace(/^::ffff:/, ""); if (normalized === "::1" || normalized === "::" || normalized.startsWith("fc") || normalized.startsWith("fd") || normalized.startsWith("fe8") || normalized.startsWith("fe9") || normalized.startsWith("fea") || normalized.startsWith("feb")) return true; const parts = normalized.split(".").map(Number); return parts.length === 4 && (parts[0] === 10 || parts[0] === 127 || parts[0] === 0 || (parts[0] === 169 && parts[1] === 254) || (parts[0] === 172 && parts[1]! >= 16 && parts[1]! <= 31) || (parts[0] === 192 && parts[1] === 168)); }
async function validate(url: URL, resolver: typeof lookup): Promise<void> { if (!["http:", "https:"].includes(url.protocol) || url.username || url.password) throw new Error("web reference must be an HTTP(S) URL without credentials"); if (url.hostname === "localhost") throw new Error("web reference target is local or private"); const addresses = netIsIP(url.hostname) ? [{ address: url.hostname }] : await resolver(url.hostname, { all: true }); if (!addresses.length || addresses.some((item) => privateAddress(item.address))) throw new Error("web reference target is local or private"); }
export async function fetchWebReference(input: string, options: WebOptions = {}): Promise<WebReference> { const fetcher = options.fetcher ?? fetch; const resolver = options.resolver ?? lookup; const maxBytes = options.maxBytes ?? 524288; let url: URL; try { url = new URL(input); } catch { throw new Error("/ask --web requires one explicit valid URL"); }
  for (let redirect = 0; redirect <= (options.maxRedirects ?? 3); redirect++) { await validate(url, resolver); const response = await fetcher(url, { redirect: "manual", signal: AbortSignal.timeout(options.timeoutMs ?? 15000), headers: { accept: "text/plain,text/html,application/json,application/xml;q=0.8" } }); if (response.status >= 300 && response.status < 400) { const location = response.headers.get("location"); if (!location || redirect === (options.maxRedirects ?? 3)) throw new Error("web reference redirect limit exceeded"); url = new URL(location, url); continue; } if (!response.ok) throw new Error(`web reference returned HTTP ${response.status}`); const contentType = response.headers.get("content-type")?.split(";")[0]?.trim().toLowerCase() ?? ""; if (!contentType.startsWith("text/") && !["application/json", "application/xml", "application/xhtml+xml"].includes(contentType)) throw new Error(`web reference content type is not textual: ${contentType || "unknown"}`); const declared = Number(response.headers.get("content-length")); if (Number.isFinite(declared) && declared > maxBytes) throw new Error(`web reference exceeds ${maxBytes} byte limit`); const bytes = Buffer.from(await response.arrayBuffer()); if (bytes.length > maxBytes) throw new Error(`web reference exceeds ${maxBytes} byte limit`); return { url: url.toString(), bytes: bytes.length, contentType, sha256: createHash("sha256").update(bytes).digest("hex"), content: new TextDecoder("utf-8", { fatal: true }).decode(bytes) }; }
  throw new Error("web reference redirect limit exceeded"); }
